name: Tests

on: [ push, pull_request ]

jobs:
  unit-benchmark-test:
    strategy:
      matrix:
        go: [ 1.21, 1.26 ]
        os: [ ubuntu-latest, ubuntu-24.04-arm ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}

      - name: Unit Test
        run: go test ./...

      - name: Benchmark
        run: go test -bench=. -benchmem -run=none ./...
